### ISSUE TITLE
Please give example for net48 binary

### ISSUE THREAD

**Issue by peakschris** [bazel-contrib/rules_dotnet#405]
Hi there,

I can't get a net48 binary to build, netstandard2.0 and net6.0 work fine, thank you! Could you please share an example of what a csharp_binary targeting net48 would look like? Thank you!

Chris

**Comment by purkhusid** [comment]
I'll add an example when I find the time. My bandwith is limited at the moment, but it should be the same as for other frameworks just with a different targeting pack(Microsoft.NETFramework.ReferenceAssemblies but there is a chance you will need to use https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies.net48 directly).

**Comment by purkhusid** [comment]
This should just work AFAIK after I reworked the targeting/runtime pack setup and now users should not have to add them manually.

**Comment by peakschris** [comment]
We found that two changes were required to get it to work. We have made these in a local fork:

![image](https://github.com/user-attachments/assets/0c60559b-6f83-409f-b955-e68550f81d00)

![image](https://github.com/user-attachments/assets/1d44c0dc-76c2-4d18-9af1-d70f206c45a4)

Would it be possible to upstream these?

Thanks, Chris

**Comment by purkhusid** [comment]
@peakschris This looks reasonable. What is the deal with the .Wrapper.dll and .Thunk.dll handling?

**Comment by peakschris** [comment]
Looping in @websteroy, who made the change

**Comment by websteroy** [comment]
@purkhusid The net48 package seems to contain these unmanaged dlls which, if not excluded, cause the following error:

```
error CS1509: The referenced file 'D:\udu\b\rn7jwoce\execroot\_main\external\rules_dotnet++targeting_packs_extension+nuget.microsoft.netframework.referenceassemblies.net48.v1.0.3\build\.NETFramework\v4.8\System.EnterpriseServices.Wrapper.dll' is not an assembly
error CS0009: Metadata file 'D:\udu\b\rn7jwoce\execroot\_main\external\rules_dotnet++targeting_packs_extension+nuget.microsoft.netframework.referenceassemblies.net48.v1.0.3\build\.NETFramework\v4.8\System.EnterpriseServices.Thunk.dll' could not be opened -- PE image doesn't contain managed metadata.
```

Is there a better (recommended) way to handle these?

**Comment by tomdegoede** [comment]
We ran into this issue as well. The dll's should be excluded as they are not listed in the FrameworkList.xml either. I would however prefer to make the check more strict by specifying their full names. Endswith on Wrapper or Thunk could potentially introduce false matches.

**Comment by purkhusid** [comment]
@tomdegoede Do you have an exhaustive list we can add to the package parsing? I think it's fine to keep the exclusions for .Net Framework packages hard coded if the list is fairly static.

**Comment by purkhusid** [comment]
This is now fixed on master: https://github.com/bazel-contrib/rules_dotnet/commit/dc5c27351ba40ed23cf0612949fc340df50eefa0
