### ISSUE TITLE
Source generation support

### ISSUE THREAD

**Issue by leryss** [bazel-contrib/rules_dotnet#447]
Is source generation supported ? If it is can i have some pointers on how to achieve this ?

I have tried to setup a basic example by copying the paket example and making some modifications. I've followed the microsoft  docs for setting up a simple source generator https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview

Here is the work i've done:
https://github.com/leryss/rules_dotnet/tree/source-gen-attempt/examples/source_generator

When running `bazel run //source_generator:main --@rules_dotnet//dotnet/settings:strict_deps=false` i am expecting to see an output like `Generator says hi from 'Generated Code'`. The source generator code doesnt seem to be executed.

If source generation is not supported what are the changes required to support this ?

**Comment by tomdegoede** [comment]
The main problem is that the csharp_library produces refs which are passed as /reference instead of /analyzer. In order for the gen to produce analyzers https://github.com/bazelbuild/rules_dotnet/blob/626e28effb14f87de8375186ebb59911a16b71fb/dotnet/private/rules/csharp/actions/csharp_assembly.bzl#L291 should be filled. We have achieved this with a hacky dll.endswith("Generator.dll") heuristic.

**Comment by purkhusid** [comment]
The handling of analyzers/source generators needs to reworked. I don't have the incentive to do so myself since it's not a problem for me or my company currently. I would happily receive contributions that makes the analyzer/generator support more robust.

**Comment by leryss** [comment]
@tomdegoede would it be possible to share some code snippets of the solution you found ? ive tried testing this by adding something like this :
```
    for ref in irefs.to_list():
        path = ref.path
        if path.endswith("gen_lib.dll"):
            analyzers = depset([ref] + analyzers.to_list())
            break
            
``` 
but getting `warning CS8034: Unable to load Analyzer assembly /tmp/bazel-working-directory/_main/bazel-out/k8-fastbuild-ST-c2c370ae55a9/bin/source_generator/gen_lib/netstandard2.0/ref/gen_lib.dll : Unable to load gen_lib`

@purkhusid i could work on this feature, do you think you could give me some pointers to get me started ?

**Comment by tomdegoede** [comment]
@leryss I think this is because you are adding a ref assembly instead of a lib assembly.

**Comment by leryss** [comment]
> @leryss I think this is because you are adding a ref assembly instead of a lib assembly.

can you help me with some code, im not sure how to fix this

**Comment by purkhusid** [comment]
I've got source generator support in the PR: https://github.com/bazelbuild/rules_dotnet/pull/452
Would appreciate any testing since I've not used source generators before.

**Comment by purkhusid** [comment]
This is now available on master. I'll be cutting a release soon.
