### ISSUE TITLE
How to access files in NuGet package?

### ISSUE THREAD

**Issue by agocke** [bazel-contrib/rules_dotnet#456]
Sometimes people use NuGet packages more as versioned data delivery than actual NuGet packages.

In this case, I need to access a file inside the `tools` directory of a NuGet package. I figured out that I can write something like

`@@_main~main_extension~nuget.package.name.v1.2.3.4//:tools/sub/path/file.txt`

But that's both really ugly and also contains the version number, meaning it's brittle. Is there a better way?

**Comment by purkhusid** [comment]
I added this functionality on master, will cut a release soon. Example here: https://github.com/bazel-contrib/rules_dotnet/commit/8f01bbd59abe423845958e81f6157aab02f06457

**Comment by agocke** [comment]
Thank you!

**Comment by agocke** [comment]
Ah, and the other missing piece here was `select_file`. Thanks again!
