### ISSUE TITLE
CONTRIBUTING.md is out of date; CLA information is incorrect

### ISSUE THREAD

**Issue by peakschris** [bazel-contrib/rules_dotnet#459]
Hi,

I noticed that CONTRIBUTING.md still says that signing the google CLA is required for this project. Whilst the discussion covering moving this project to bazel-contrib says that CLA will not be required for such projects:

https://github.com/orgs/bazelbuild/discussions/2
> Google CLA is no longer required for contributions to a project under bazel-contrib.

Thanks!

**Comment by purkhusid** [comment]
Thanks for highlighting this. The text has been removed!
