### ISSUE TITLE
paket.dependencies with multiple sources

### ISSUE THREAD

**Issue by phuoc001** [bazel-contrib/rules_dotnet#461]
In paket.dependencies file, Is it possible to mix  different sources from:
- https://api.nuget.org/v3/index.json
- local subdirectory containing .nupkg files?

The following configuration seems to fail:

```
storage: none
framework: net8.0
source https://api.nuget.org/v3/index.json

nuget Microsoft.AspNetCore.App.Ref 7.0.15
nuget Microsoft.NETCore.App.Ref 7.0.15

group local
    framework: net8.0
    source other-packages

    nuget my.local.nuget 13.0.3
```
I try doing this:

```
csharp_binary(
    name = "hello-world",
    srcs = [
        "Program.cs"
    ],
    target_frameworks = [ "net8.0" ],
    targeting_packs = [
        "@paket.main//microsoft.aspnetcore.app.ref",
        "@paket.main//microsoft.netcore.app.ref",
    ],
    deps = [
        "@paket.local//newtonsoft.json",
    ],
)

```
But the "bazel build" command failed:

`ERROR: /private/var/tmp/_bazel_pta/1e6e2676e185910c118ab175fa8c6d5c/external/paket.local/newtonsoft.json/13.0.3/BUILD.bazel:5:15: @paket.local//newtonsoft.json/13.0.3:13.0.3 depends on @nuget.newtonsoft.json.v13.0.3//:newtonsoft.json.13.0.3.nupkg in repository @nuget.newtonsoft.json.v13.0.3 which failed to fetch. no such package '@nuget.newtonsoft.json.v13.0.3//': java.io.IOException: Bad URL: other-packages/package/newtonsoft.json/13.0.3`

**Comment by purkhusid** [comment]
No, this is not possible. Paket does support referencing file with `http file://path/to/file` but that is not supported in rules_dotnet.
